#RetroBox Fastline file

default_platform(:android)

platform :android do

  desc "Assemble Build"
  lane :assemble_build do |options|
    gradle(
      task: "assemble",
      flavor: options[:build_flavor],
      build_type: options[:build_type]
    )
  end

  desc "Run Unit Tests"
  lane :unit_tests do |options|
    gradle(
      task: "test",
      flavor: options[:build_flavor],
      build_type: options[:build_type]
    )
  end

  desc "Run UI Test in Firebase Test Lab"
  lane :instrumentation_tests_testlab do |options|
    assemble_build(build_flavor:options[:build_flavor], build_type:"Debug")
    @app_apk = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

    assemble_build(build_flavor:options[:build_flavor] + "Debug", build_type:"AndroidTest")
    @android_test_apk = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    
    run_tests_firebase_testlab(
      project_id:"retrobox-app",
      app_apk: @app_apk,
      android_test_apk: @android_test_apk,
      devices: [
        {
            model: "Nexus6P",
            version: "27"
        }
      ], 
      delete_firebase_files: true
    )
  end

  desc "Release Deployment"
  lane :release do |options|
    assemble_build(build_flavor:"Pro", build_type:"Release")
    upload_to_play_store(
        apk: Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    )
    crashlytics(
        apk_path:Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
        api_token:'aee4492cf369d809aef43858bff0ebe71598851b',
        build_secret:'f0ae8fb4562bc616993490b07f6020fd893759e771616704aca9bc8f035f333c'
    )
  end
end
