# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Assemble Build"
  lane :assemble_build do |options|
    gradle(
      task: "assemble",
      flavor: options[:build_flavor],
      build_type: options[:build_type]
    )
  end

  desc "Run Unit Tests"
  lane :unit_tests do |options|
    gradle(
      task: "test",
      flavor: options[:build_flavor],
      build_type: options[:build_type]
    )
  end

  desc "Run UI Test in Firebase Test Lab"
  lane :instrumentation_tests_testlab do |options|
    assemble_build(build_flavor:options[:build_flavor], build_type:"Debug")
    @app_apk = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    
    assemble_build(build_flavor:options[:build_flavor] + "Debug", build_type:"AndroidTest")
    @android_test_apk = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    
    run_tests_firebase_testlab(
      project_id:"retrobox-app",
      app_apk: @app_apk,
      android_test_apk: @android_test_apk,
      devices: [
        {
            model: "Nexus6P",
            version: "27"
        }
      ], 
      delete_firebase_files: true
    )
  end
end
